### ISSUE TITLE
Add licence file.

### ISSUE THREAD

**Issue by gavinballard** [discolabs/custard-js#4]
Now that we've open-sourced Custard, we should select and add an open source licence for the framework.

**Comment by gavinballard** [comment]
@PuZZleDucK - maybe something you'd have some input on?

**Comment by PuZZleDucK** [comment]
Just saw this now... but it has been in the back of my mind.

The `Contributing.md` file suggests contributions to the project be licenced MIT.
It's also a pretty good assumption the library would be included in a proprietary work and that's another good fit for MIT.
MIT would have also been my best suggestion on the basis it's the license with the lowest commercial friction and most likely to encourage easy adoption.

**Comment by gavinballard** [comment]
Thanks @PuZZleDucK - MIT is my go-to, but good to get confirmation from the expert!

**Comment by PuZZleDucK** [comment]
How about a PR to boot: #8

**Comment by gavinballard** [comment]
Closed by #8.
