### ISSUE TITLE
Instructions in `CONTRIBUTING.md` fail to execute

### ISSUE THREAD

**Issue by PuZZleDucK** [discolabs/custard-js#7]
Currently the `Submitting a Pull Request` section of the `CONTRIBUTING.md` doc suggests that contributors fork the repo, clone it, then run `yarn install` and `yarn test` commands.

The `yarn test` command fails as there is no test library installed nor a script command in `package.json`.

**Comment by PuZZleDucK** [comment]
I'm proposing adding jest and a couple of simple smoke tests

**Comment by gavinballard** [comment]
> I'm proposing adding jest and a couple of simple smoke tests

@PuZZleDucK sounds like a good approach to me! My JS testing game is pretty poor.
